# Generated by Django 2.2.2 on 2019-08-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('body', models.TextField()),
                ('priority', models.IntegerField(default=3)),
                ('due', models.DateField(null=True)),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
